const express = require('express');
const router = express.Router();
const accountController = require('../controllers/account');
const authentication = require('../middlewares/authentication');
const locals = require('../middlewares/locals');
router.get('/register', accountController.getRegister);
router.post('/register', accountController.postRegister);
router.get('/login', accountController.getLogin);
router.post('/login', accountController.postLogin);
router.get('/reset-password', accountController.getReset);
router.post('/reset-password', accountController.postReset);
router.get('/reset-password/:token', accountController.getNewPassword);
router.post('/new-password', accountController.postNewPassword);
router.get('/profile', authentication, locals, accountController.getProfile);
router.post('/profile', locals, accountController.postProfile);
router.get('/logout', accountController.getLogout);
router.get('/activity-logs', authentication, locals, accountController.getActivityLogs);
module.exports = router;